name: Build Docker Image

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      APP_NAME: "rdurica/xxxx"  # <-- Name of application

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      -
        name: Build Docker images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            compose.prod.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      -
        name: Start services
        run: docker compose up --wait

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        uses: docker/bake-action@v4
        with:
          pull: true
          push: true
          files: |
            compose.prod.yaml
          set: |
            *.tags=${{ env.APP_NAME }}:${{ github.ref_name }}
            *.tags=${{ env.APP_NAME }}:latest
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{ github.ref }},mode=max

      - name: Push Image Confirmation
        run: echo "Docker image successfully built and pushed."